version: '2'
services:

  wordpress:
    image: wordpress:latest
    #container_name: $COMPOSE_PROJECT_NAME
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
        - 80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /srv/docker-data/${COMPOSE_PROJECT_NAME}/www:/var/www/html
    networks:
      - proxy
      - wordpress_net

    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.wordpress-${COMPOSE_PROJECT_NAME}.service=$COMPOSE_PROJECT_NAME"
      - "traefik.http.routers.wordpress-${COMPOSE_PROJECT_NAME}.entrypoints=http"
      - "traefik.http.routers.wordpress-${COMPOSE_PROJECT_NAME}.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.middlewares.wordpress-${COMPOSE_PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress-${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}-https-redirect"
      - "traefik.http.routers.wordpress-${COMPOSE_PROJECT_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.wordpress-${COMPOSE_PROJECT_NAME}-secure.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.routers.wordpress-${COMPOSE_PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.wordpress-${COMPOSE_PROJECT_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.wordpress${COMPOSE_PROJECT_NAME}-secure.service=$COMPOSE_PROJECT_NAME"
      - "traefik.docker.network=proxy"

  db:
    image: mysql:5.7
    #container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /srv/docker-data/$COMPOSE_PROJECT_NAME/db:/var/lib/mysql:rw
    networks:
      - wordpress_net
      
networks:
  proxy:
    external: 
      name: proxy
  wordpress_net:
